name: cep_searcher
description: Consultor de CEP
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  equatable: ^1.0.2
  retrofit: ^1.0.1+1
  json_serializable: 3.2.5
  dio: ^3.0.8
  mask_text_input_formatter: ^1.0.5
  bloc: 3.0.0
  flutter_bloc: 3.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  retrofit_generator: ^1.0.2+2
  build_runner: ^1.7.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true